doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        profiling_collect_backtrace: '%kernel.debug%'
#        use_savepoints: true
        types:
            uuid_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\UuidType
            # datetime
            create_date_type: App\Infrastructure\Database\Doctrine\SQL\Type\Date\CreateDateType
            publication_date_type: App\Infrastructure\Database\Doctrine\SQL\Type\Date\PublicationDateType
            request_date_type: App\Infrastructure\Database\Doctrine\SQL\Type\Date\RequestDateType
            # int
            test_number_type: App\Infrastructure\Database\Doctrine\SQL\Type\Integer\TestNumberType
            views_type: App\Infrastructure\Database\Doctrine\SQL\Type\Integer\ViewsType
            # object
            picture_type: App\Infrastructure\Database\Doctrine\SQL\Type\Object\PictureType
            # string
            categories_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\CategoriesType
            content_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\ContentType
            email_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\EmailType
            nickname_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\NicknameType
            password_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\PasswordType
            picture_alt_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\PictureAltType
            picture_extension_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\PictureExtensionType
            picture_source_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\PictureSourceType
            picture_name_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\PictureNameType
            request_ip_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\RequestIPType
            request_route_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\RequestRouteType
            role_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\RoleType
            slug_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\SlugType
            test_name_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\TestNameType
            title_type: App\Infrastructure\Database\Doctrine\SQL\Type\String\TitleType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine_sql/'
                prefix: 'App\Domain'
                type: xml
            Infrastructure:
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine_sql_infrastructure'
                prefix: 'App\Infrastructure'
                type: xml

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'


#when@prod:
#    doctrine:
#        dbal:
#            url: '%env(resolve:DATABASE_URL)%'
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool
#
#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
