nelmio_cors:
    defaults:
        allow_headers: [ '*' ]
        allow_methods: [ '*' ]
        allow_origin: [ '%env(FRONT_HOST)%', 'localhost:3000' ]
        expose_headers: [ '*' ]
        max_age: 3600
        origin_regex: true
    paths:
        '^/api/login':
            allow_headers: [ '*' ]
            allow_origin: [ '%env(FRONT_HOST)%', 'localhost:3000' ]
            allow_methods: [ 'POST' ]
            expose_headers: [ '*' ]
            max_age: 3600
            origin_regex: true
        '^/api/':
            allow_headers: [ '*' ]
            allow_origin: [ '%env(FRONT_HOST)%', 'localhost:3000' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTIONS' ]
            expose_headers: [ '*' ]
            max_age: 3600
            origin_regex: true

