framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
#        App\Application\Test\Command\CreateTest:
#            properties:
#                name:
#                    - NotBlank: ~

#App\Application\Test\Command\CreateTest:
#    properties:
#        name:
#            - NotBlank: ~

#App\Domain\Shared\ValueObject\String\TestNameVO:
#    properties:
#        value:
#            - NotBlank: ~


when@test:
    framework:
        validation:
            not_compromised_password: false
