<?php

declare(strict_types=1);

namespace App\Application\Shared;

enum Error: string
{
    case INVALID_DATA = 'INVALID_DATA';

    # ARTICLE #
    case ARTICLE_SLUG_ALREADY_EXIST = 'ARTICLE_SLUG_ALREADY_EXIST';
    case ARTICLE_DOES_NOT_EXIST = 'ARTICLE_DOES_NOT_EXIST';

    # PICTURE #
    case PICTURE_NOT_FOUND = 'PICTURE_NOT_FOUND';
    case PICTURE_SOURCE_ALREADY_EXIST = 'PICTURE_SOURCE_ALREADY_EXIST';
    case SAVE_PICTURE_EXCEPTION = 'SAVE_PICTURE_EXCEPTION';

    # TEST #
    case TEST_NOT_FOUND = 'TEST_NOT_FOUND';

    # USER #
    case USER_EMAIL_ALREADY_EXIST = 'USER_EMAIL_ALREADY_EXIST';
    case USER_NICKNAME_ALREADY_EXIST = 'USER_NICKNAME_ALREADY_EXIST';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case WRONG_PASSWORD = 'WRONG_PASSWORD';
}
