services:
    php_server:
        build: images/php
        image: gblog-php-server
        container_name: gblog-php-server
        user: ${LOCAL_UID}:${LOCAL_GID}
        working_dir: /home/application/api/
        ports:
            - ${WEB_SERVER_PORT}:80
            - ${API_SERVER_PORT}:81
            - ${IMAGE_SERVER_PORT}:82
        volumes:
            - ${V_SERVER_APACHE_PORTS}:/etc/apache2/ports.conf
            - ${V_SERVER_APACHE_SITES}:/etc/apache2/sites-enabled/
            - ${V_SERVER_SOURCE_API}:/home/application/api/
            - ${V_SERVER_SOURCE_WEB}:/home/application/web
            - ${V_SERVER_UPLOADS}:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - XDEBUG_MODE=off

    mariadb:
        image: mariadb:10.11
        container_name: gblog-mariadb
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    phpmyadmin:
        image: phpmyadmin:5.2
        container_name: gblog-phpmyadmin
        ports:
            - ${PORT_PHPMYADMIN}:80
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - PMA_HOST=gblog-mariadb

#    mongo:
#        image: mongo:4.0.3
#        container_name: gblog-mongo
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#        restart: unless-stopped
#        ports:
#            - ${MONGO_SERVER_PORT}:27017
#        volumes:
#            - ${V_MONGO_USERS}:/docker-entrypoint-initdb.d/mongo-init.js
#
#    mongo-express:
#        image: mongo-express
#        container_name: gblog-mexpress
#        environment:
#            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
#            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
#            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/?authSource=admin
#            - ME_CONFIG_BASICAUTH_USERNAME=${MEXPRESS_USER}
#            - ME_CONFIG_BASICAUTH_PASSWORD=${MEXPRESS_PASSWORD}
#        restart: unless-stopped
#        ports:
#            - ${MEXPRESS_SERVER_PORT}:8081

    node:
        image: node:20.3-alpine
        container_name: gblog-node
        tty: true
#        user: ${LOCAL_UID}:${LOCAL_GID}
        working_dir: /home/application
        ports:
            - ${NODE_SERVER_PORT}:3000
        volumes:
            - ${V_SERVER_SOURCE_WEB}:/home/application/
