export enum Errors {
    PICTURE_NOT_FOUND = 'PICTURE_NOT_FOUND',
    PICTURE_ALT_VALUE_TOO_SHORT = 'PICTURE_ALT_VALUE_TOO_SHORT',
    PICTURE_NAME_VALUE_TOO_SHORT = 'PICTURE_NAME_VALUE_TOO_SHORT',
    SLUG_VALUE_CANNOT_BE_EMPTY = 'SLUG_VALUE_CANNOT_BE_EMPTY',
    SLUG_VALUE_TOO_SHORT = 'SLUG_VALUE_TOO_SHORT',
    TITLE_VALUE_TOO_SHORT = 'TITLE_VALUE_TOO_SHORT',
}
